# Generated by Django 4.0.4 on 2022-04-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abilities', models.CharField(max_length=200)),
                ('real_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date']},
        ),
        migrations.AddField(
            model_name='heros',
            name='villians',
            field=models.ManyToManyField(to='main_app.villian'),
        ),
    ]
